omap: Omit fastboot.userdata_size related errors
commit 19d141a0f90c640a8d5ed699745cbc8169918945 upstream.

When using regular $partitions variable (for Linux boot), we can see
some unwanted messages:

> ERROR: cannot find partition: 'userdata'

> at arch/arm/mach-omap2/utils.c:96/omap_mmc_get_part_size()
> Warning: fastboot.userdata_size: unable to calc

Let's remove those, as missing 'userdata' partition is correct behavior
for Linux partition, and we don't want to see some Android-related
messages in this case.

Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>
[praneeth@ti.com: rebase and resolve merge-conflict in
arch/arm/mach-omap2/utils.c in commit 19d141a0f90c from v2017.11]
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>