usb: gadget: ether: fix build breakage
Building with ARM-based am43xx_evm_config results in

/datalocal/Sekhar/u-boot-am33x/drivers/usb/gadget/ether.c:2340:20: error: ‘USB_INIT_DEVICE’ undeclared (first use in this function)

Fix this.

Fixes: 0db60451ac0a ("usb: gadget: ether: initialize and cleanup gadget from ether gadget")
Signed-off-by: Sekhar Nori <nsekhar@ti.com>