spl: usb: streamline usage of config macros
Currently, CONFIG_SPL_USB_SUPPORT and CONFIG_SPL_USB_HOST_SUPPORT
are used quite interchangeably and not consistently. And, there is
no macro which identifies generic USB support in SPL.

Streamline usage of config macros used for USB support.
After this patch, the macros mean:

- CONFIG_SPL_USB_HOST_SUPPORT	: SPL USB host support
- CONFIG_SPL_USBETH_SUPPORT	: SPL USB Eth gadget support
- CONFIG_SPL_USB_SUPPORT	: SPL USB common support

As a nice side-effect, this fixes build error in AM335x USB
support due to missing dependencies.

drivers/usb/gadget/ether.c:2526: undefined reference to `board_usb_cleanup'
drivers/usb/gadget/built-in.o: In function `usb_eth_init':
drivers/usb/gadget/ether.c:2341: undefined reference to `board_usb_init'